name: PR Build Adding a comment with the build scan
on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

    - name: PR Build
      id: read_file
      run: |
        ./gradlew assembleDebug
        content="$(cat temp_build_scan_url.txt)"
        echo "::set-output name=content::$content"
      env:
        PR_CI_BUILD: true
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}  

    - name: Comment on PR
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issue_number = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const comment = `${{ steps.read_file.outputs.content }}`;
          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number,
            body: comment
          });