name: PR Build Adding a comment with the build scan
on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: PR Build
      id: read_file
      run: |
        ./gradlew assembleDebug
        gradle_exit_code=$?
        content="$(cat temp_build_scan_url.txt)"
        echo $content
        echo "::set-output name=content::$content"
        exit $gradle_exit_code
      continue-on-error: true  
      env:
        PR_CI_BUILD: true
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}  

    - name: Comment on PR
      if: always()
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issue_number = context.payload.pull_request.number;
          const comment = `2323${{ steps.read_file.outputs.content }}`;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: comment
          });